name: Docker-build-dev
on:
  push:
    branches: [ dev ]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set up docker
      run: |
        apt update
        apt install -y docker.io         
    - name: Build/Push
      run: |
        echo ${{ secrets.GIT_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin git.d3vyce.fr
        docker build -t d3vyce.fr .
        docker tag d3vyce.fr git.d3vyce.fr/d3vyce/d3vyce.fr:dev
        docker push git.d3vyce.fr/d3vyce/d3vyce.fr:dev
