name: Docker-build
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set up docker
      run: |
        apt update
        apt install -y docker.io
        echo '{ "insecure-registries":["10.0.0.3:5000"] }' > /etc/docker/daemon.json
        systemctl restart docker.service
    - name: Build/Push
      run: |
        docker build -t d3vyce.fr .
        docker tag d3vyce.fr 10.0.0.3:5000/d3vyce
        docker push 10.0.0.3:5000/d3vyce