name: Docker-build
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set up docker
      run: |
        apt update
        apt install -y docker.io 
    - name: Build/Push
      run: |
        docker login -u ${{ github.actor }} -p ${{ secrets.GIT_TOKEN }} git.d3vyce.fr
        docker build -t d3vyce.fr .
        docker tag d3vyce.fr git.d3vyce.fr/d3vyce/d3vyce.fr:latest
        docker push git.d3vyce.fr/d3vyce/d3vyce.fr:latest