name: Docker-build
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - test: test variable
      run: echo "username: ${{ github.actor }}"
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: git.d3vyce.fr
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_TOKEN }}
    - name: Build/Push
      run: |
        docker build -t d3vyce.fr .
        docker push git.d3vyce.fr/d3vyce/d3vyce.fr:latest